apiVersion: v1
kind: Namespace
metadata:
  name: api-fintech
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-fintech
  namespace: api-fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-fintech
  template:
    metadata:
      labels:
        app: api-fintech
    spec:
      containers:
        - name: api-fintech
          image: pcisnerp/finbiz_api_app:0.4.0
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-fintech
  namespace: api-fintech
spec:
  selector:
    app: api-fintech
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
